// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enceladus.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Saturn.Backends.Protocols.Enceladus {

  /// <summary>Holder for reflection information generated from enceladus.proto</summary>
  public static partial class EnceladusReflection {

    #region Descriptor
    /// <summary>File descriptor for enceladus.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnceladusReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9lbmNlbGFkdXMucHJvdG8SE3Byb3RvY29scy5lbmNlbGFkdXMaDGNvbW1v",
            "bi5wcm90byJ0ChRQb3N0UmVzb3VyY2VSZXNwb25zZRIuCgZjb21tb24YASAB",
            "KAsyHi5wcm90b2NvbHMuY29tbW9uLkNvbW1vblN0YXR1cxIsCghyZXNvdXJj",
            "ZRgCIAEoCzIaLnByb3RvY29scy5jb21tb24uUmVzb3VyY2UiMgoaUG9zdFBy",
            "ZXZpZXdSZXNvdXJjZVJlcXVlc3QSFAoMZW5jb2RlZEltYWdlGAEgASgJIokB",
            "ChtQb3N0UHJldmlld1Jlc291cmNlUmVzcG9uc2USLgoGY29tbW9uGAEgASgL",
            "Mh4ucHJvdG9jb2xzLmNvbW1vbi5Db21tb25TdGF0dXMSOgoPcHJldmlld1Jl",
            "c291cmNlGAIgASgLMiEucHJvdG9jb2xzLmNvbW1vbi5QcmV2aWV3UmVzb3Vy",
            "Y2UiMAoQUG9zdEFkbWluUmVxdWVzdBIKCgJpZBgBIAEoCRIQCghwYXNzd29y",
            "ZBgCIAEoCSJDChFQb3N0QWRtaW5SZXNwb25zZRIuCgZjb21tb24YASABKAsy",
            "Hi5wcm90b2NvbHMuY29tbW9uLkNvbW1vblN0YXR1c0ImqgIjU2F0dXJuLkJh",
            "Y2tlbmRzLlByb3RvY29scy5FbmNlbGFkdXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Saturn.Backends.Protocols.Common.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Saturn.Backends.Protocols.Enceladus.PostResourceResponse), global::Saturn.Backends.Protocols.Enceladus.PostResourceResponse.Parser, new[]{ "Common", "Resource" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Saturn.Backends.Protocols.Enceladus.PostPreviewResourceRequest), global::Saturn.Backends.Protocols.Enceladus.PostPreviewResourceRequest.Parser, new[]{ "EncodedImage" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Saturn.Backends.Protocols.Enceladus.PostPreviewResourceResponse), global::Saturn.Backends.Protocols.Enceladus.PostPreviewResourceResponse.Parser, new[]{ "Common", "PreviewResource" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Saturn.Backends.Protocols.Enceladus.PostAdminRequest), global::Saturn.Backends.Protocols.Enceladus.PostAdminRequest.Parser, new[]{ "Id", "Password" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Saturn.Backends.Protocols.Enceladus.PostAdminResponse), global::Saturn.Backends.Protocols.Enceladus.PostAdminResponse.Parser, new[]{ "Common" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PostResourceResponse : pb::IMessage<PostResourceResponse> {
    private static readonly pb::MessageParser<PostResourceResponse> _parser = new pb::MessageParser<PostResourceResponse>(() => new PostResourceResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PostResourceResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Saturn.Backends.Protocols.Enceladus.EnceladusReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostResourceResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostResourceResponse(PostResourceResponse other) : this() {
      common_ = other.common_ != null ? other.common_.Clone() : null;
      resource_ = other.resource_ != null ? other.resource_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostResourceResponse Clone() {
      return new PostResourceResponse(this);
    }

    /// <summary>Field number for the "common" field.</summary>
    public const int CommonFieldNumber = 1;
    private global::Saturn.Backends.Protocols.Common.CommonStatus common_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Saturn.Backends.Protocols.Common.CommonStatus Common {
      get { return common_; }
      set {
        common_ = value;
      }
    }

    /// <summary>Field number for the "resource" field.</summary>
    public const int ResourceFieldNumber = 2;
    private global::Saturn.Backends.Protocols.Common.Resource resource_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Saturn.Backends.Protocols.Common.Resource Resource {
      get { return resource_; }
      set {
        resource_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PostResourceResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PostResourceResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Common, other.Common)) return false;
      if (!object.Equals(Resource, other.Resource)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (common_ != null) hash ^= Common.GetHashCode();
      if (resource_ != null) hash ^= Resource.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (common_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Common);
      }
      if (resource_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Resource);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (common_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Common);
      }
      if (resource_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Resource);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PostResourceResponse other) {
      if (other == null) {
        return;
      }
      if (other.common_ != null) {
        if (common_ == null) {
          Common = new global::Saturn.Backends.Protocols.Common.CommonStatus();
        }
        Common.MergeFrom(other.Common);
      }
      if (other.resource_ != null) {
        if (resource_ == null) {
          Resource = new global::Saturn.Backends.Protocols.Common.Resource();
        }
        Resource.MergeFrom(other.Resource);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (common_ == null) {
              Common = new global::Saturn.Backends.Protocols.Common.CommonStatus();
            }
            input.ReadMessage(Common);
            break;
          }
          case 18: {
            if (resource_ == null) {
              Resource = new global::Saturn.Backends.Protocols.Common.Resource();
            }
            input.ReadMessage(Resource);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PostPreviewResourceRequest : pb::IMessage<PostPreviewResourceRequest> {
    private static readonly pb::MessageParser<PostPreviewResourceRequest> _parser = new pb::MessageParser<PostPreviewResourceRequest>(() => new PostPreviewResourceRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PostPreviewResourceRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Saturn.Backends.Protocols.Enceladus.EnceladusReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostPreviewResourceRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostPreviewResourceRequest(PostPreviewResourceRequest other) : this() {
      encodedImage_ = other.encodedImage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostPreviewResourceRequest Clone() {
      return new PostPreviewResourceRequest(this);
    }

    /// <summary>Field number for the "encodedImage" field.</summary>
    public const int EncodedImageFieldNumber = 1;
    private string encodedImage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string EncodedImage {
      get { return encodedImage_; }
      set {
        encodedImage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PostPreviewResourceRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PostPreviewResourceRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EncodedImage != other.EncodedImage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (EncodedImage.Length != 0) hash ^= EncodedImage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (EncodedImage.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EncodedImage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (EncodedImage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EncodedImage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PostPreviewResourceRequest other) {
      if (other == null) {
        return;
      }
      if (other.EncodedImage.Length != 0) {
        EncodedImage = other.EncodedImage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            EncodedImage = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PostPreviewResourceResponse : pb::IMessage<PostPreviewResourceResponse> {
    private static readonly pb::MessageParser<PostPreviewResourceResponse> _parser = new pb::MessageParser<PostPreviewResourceResponse>(() => new PostPreviewResourceResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PostPreviewResourceResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Saturn.Backends.Protocols.Enceladus.EnceladusReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostPreviewResourceResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostPreviewResourceResponse(PostPreviewResourceResponse other) : this() {
      common_ = other.common_ != null ? other.common_.Clone() : null;
      previewResource_ = other.previewResource_ != null ? other.previewResource_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostPreviewResourceResponse Clone() {
      return new PostPreviewResourceResponse(this);
    }

    /// <summary>Field number for the "common" field.</summary>
    public const int CommonFieldNumber = 1;
    private global::Saturn.Backends.Protocols.Common.CommonStatus common_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Saturn.Backends.Protocols.Common.CommonStatus Common {
      get { return common_; }
      set {
        common_ = value;
      }
    }

    /// <summary>Field number for the "previewResource" field.</summary>
    public const int PreviewResourceFieldNumber = 2;
    private global::Saturn.Backends.Protocols.Common.PreviewResource previewResource_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Saturn.Backends.Protocols.Common.PreviewResource PreviewResource {
      get { return previewResource_; }
      set {
        previewResource_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PostPreviewResourceResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PostPreviewResourceResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Common, other.Common)) return false;
      if (!object.Equals(PreviewResource, other.PreviewResource)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (common_ != null) hash ^= Common.GetHashCode();
      if (previewResource_ != null) hash ^= PreviewResource.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (common_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Common);
      }
      if (previewResource_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PreviewResource);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (common_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Common);
      }
      if (previewResource_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PreviewResource);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PostPreviewResourceResponse other) {
      if (other == null) {
        return;
      }
      if (other.common_ != null) {
        if (common_ == null) {
          Common = new global::Saturn.Backends.Protocols.Common.CommonStatus();
        }
        Common.MergeFrom(other.Common);
      }
      if (other.previewResource_ != null) {
        if (previewResource_ == null) {
          PreviewResource = new global::Saturn.Backends.Protocols.Common.PreviewResource();
        }
        PreviewResource.MergeFrom(other.PreviewResource);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (common_ == null) {
              Common = new global::Saturn.Backends.Protocols.Common.CommonStatus();
            }
            input.ReadMessage(Common);
            break;
          }
          case 18: {
            if (previewResource_ == null) {
              PreviewResource = new global::Saturn.Backends.Protocols.Common.PreviewResource();
            }
            input.ReadMessage(PreviewResource);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PostAdminRequest : pb::IMessage<PostAdminRequest> {
    private static readonly pb::MessageParser<PostAdminRequest> _parser = new pb::MessageParser<PostAdminRequest>(() => new PostAdminRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PostAdminRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Saturn.Backends.Protocols.Enceladus.EnceladusReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostAdminRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostAdminRequest(PostAdminRequest other) : this() {
      id_ = other.id_;
      password_ = other.password_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostAdminRequest Clone() {
      return new PostAdminRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PostAdminRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PostAdminRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Password != other.Password) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PostAdminRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PostAdminResponse : pb::IMessage<PostAdminResponse> {
    private static readonly pb::MessageParser<PostAdminResponse> _parser = new pb::MessageParser<PostAdminResponse>(() => new PostAdminResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PostAdminResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Saturn.Backends.Protocols.Enceladus.EnceladusReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostAdminResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostAdminResponse(PostAdminResponse other) : this() {
      common_ = other.common_ != null ? other.common_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostAdminResponse Clone() {
      return new PostAdminResponse(this);
    }

    /// <summary>Field number for the "common" field.</summary>
    public const int CommonFieldNumber = 1;
    private global::Saturn.Backends.Protocols.Common.CommonStatus common_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Saturn.Backends.Protocols.Common.CommonStatus Common {
      get { return common_; }
      set {
        common_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PostAdminResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PostAdminResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Common, other.Common)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (common_ != null) hash ^= Common.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (common_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Common);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (common_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Common);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PostAdminResponse other) {
      if (other == null) {
        return;
      }
      if (other.common_ != null) {
        if (common_ == null) {
          Common = new global::Saturn.Backends.Protocols.Common.CommonStatus();
        }
        Common.MergeFrom(other.Common);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (common_ == null) {
              Common = new global::Saturn.Backends.Protocols.Common.CommonStatus();
            }
            input.ReadMessage(Common);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
