// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Prometheus.Models;
//
//    var element = RssElement.FromJson(jsonString);
using System;
using System.Xml.Serialization;
using System.Collections.Generic;

namespace Saturn.Backends.Commons
{
    namespace Models
    {
        /* 
         Licensed under the Apache License, Version 2.0

         http://www.apache.org/licenses/LICENSE-2.0
         */

        [XmlRoot(ElementName = "item")]
        public class Item
        {
            [XmlElement(ElementName = "title")]
            public string Title { get; set; }
            [XmlElement(ElementName = "description")]
            public string Description { get; set; }
            [XmlElement(ElementName = "pubDate")]
            public string PubDate { get; set; }
            [XmlElement(ElementName = "link")]
            public string Link { get; set; }
        }

        [XmlRoot(ElementName = "channel")]
        public class Channel
        {
            [XmlElement(ElementName = "title")]
            public string Title { get; set; }
            [XmlElement(ElementName = "link")]
            public string Link { get; set; }
            [XmlElement(ElementName = "description")]
            public string Description { get; set; }
            [XmlElement(ElementName = "language")]
            public string Language { get; set; }
            [XmlElement(ElementName = "copyright")]
            public string Copyright { get; set; }
            [XmlElement(ElementName = "lastBuildDate")]
            public string LastBuildDate { get; set; }
            [XmlElement(ElementName = "item")]
            public List<Item> Item { get; set; }
        }

        [XmlRoot(ElementName = "rss")]
        public class RssElement
        {
            [XmlElement(ElementName = "channel")]
            public Channel Channel { get; set; }

            [XmlAttribute(AttributeName = "version")]
            public string Version { get; set; }
        }
    }
}